# docker run -d -i -t --name ubuntu ubuntu
version: "3.8"

services:
  ubuntu:
    image: ubuntu
    tty: true # Terminal - validar -it
    container_name: ubuntu # Name
    volumes:
      - "./main.py:/main.py"

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - test-curso
    #  - frontend # Se agrega el contenedor a esta red - OLD

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3312:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

volumes:
  db-data:

networks:
  test-curso:
    external: true
  # frontend: # OLD
  #   external:
  #     name: docker-curso # This network should be created